version: 2
updates:
- package-ecosystem: pip
  directory: "/server/requirements"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/{{ cookiecutter.project_slug }}/requirements"
  schedule:
    interval: daily
